import React, { useState, useEffect } from 'react';
import { auth } from '../services/auth';
import { Bike, AlertCircle } from 'lucide-react';

export default function LoginPage() {
  const [code, setCode] = useState('');
  const [mobile, setMobile] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    const role = auth.getRole();
    if (role === 'rider') {
      window.location.href = '/';
    }
  }, []);

  const handleLogin = async (e) => {
    e.preventDefault();
    if (!code || code.trim().length < 4) {
      setError('Please enter a valid 8-digit access code');
      return;
    }
    
    setLoading(true);
    setError(null);

    try {
      const role = await auth.loginWithCode(code, mobile);
      if (role === 'rider') {
        window.location.href = '/';
      } else {
        setError('Unrecognized role mapped to this code.');
      }
    } catch (err) {
      setError(err.message || 'Failed to authenticate');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column', backgroundColor: 'var(--color-bg, #f8fafc)' }}>
      {/* Hero Header Area */}
      <div style={{ 
        background: 'linear-gradient(135deg, #F8CB46 0%, #eab308 100%)',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        borderBottomLeftRadius: '32px',
        borderBottomRightRadius: '32px',
        padding: '40px 24px 32px',
        color: '#000',
        boxShadow: '0 4px 20px rgba(234, 179, 8, 0.2)'
      }}>
        <div style={{
          width: '64px',
          height: '64px',
          backgroundColor: '#000',
          borderRadius: '18px',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          marginBottom: '14px',
          boxShadow: '0 8px 20px rgba(0,0,0,0.15)'
        }}>
          <Bike size={32} color="#0f172a" />
        </div>
        <h1 style={{ fontSize: '28px', fontWeight: '900', margin: 0, letterSpacing: '-0.5px' }}>Zipit Rider Portal</h1>
        <p style={{ fontSize: '14px', fontWeight: '700', opacity: 0.85, marginTop: '6px' }}>
          Deliver fast. Earn fast.
        </p>
      </div>

      {/* Login Form */}
      <div style={{ padding: '32px 24px', flex: 1, maxWidth: '440px', margin: '0 auto', width: '100%' }}>
        <h2 style={{ fontSize: '20px', fontWeight: '800', marginBottom: '8px', color: 'var(--color-text)' }}>
          Rider Sign In
        </h2>
        <p style={{ fontSize: '13.5px', color: 'var(--color-text-light)', marginBottom: '24px' }}>
          Enter the Access Code generated by Admin to access your delivery dashboard.
        </p>
        
        {error && (
          <div style={{ background: '#fee2e2', color: '#dc2626', border: '1px solid #fca5a5', padding: '12px 16px', borderRadius: '12px', marginBottom: '20px', fontSize: '13.5px', fontWeight: '600', lineHeight: '1.4', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <AlertCircle size={18} style={{ flexShrink: 0 }} />
            <span>{error}</span>
          </div>
        )}

        <form onSubmit={handleLogin} style={{ display: 'flex', flexDirection: 'column', gap: '18px' }}>
          <div>
            <label style={{ display: 'block', fontSize: '13px', fontWeight: '700', color: 'var(--color-text)', marginBottom: '8px' }}>
              8-Digit Access Code <span style={{ color: '#dc2626' }}>*</span>
            </label>
            <input 
              type="text" 
              placeholder="e.g. RIDER8821" 
              value={code}
              onChange={e => setCode(e.target.value.toUpperCase())}
              required
              maxLength={12}
              style={{ 
                width: '100%', 
                padding: '16px', 
                borderRadius: '14px', 
                border: '1.5px solid var(--color-border)', 
                backgroundColor: '#ffffff',
                fontSize: '17px',
                fontWeight: '800',
                letterSpacing: '2px',
                textAlign: 'center',
                boxShadow: '0 2px 6px rgba(0,0,0,0.03)'
              }}
            />
          </div>

          <div>
            <label style={{ display: 'block', fontSize: '13px', fontWeight: '700', color: 'var(--color-text)', marginBottom: '4px' }}>
              Mobile Number <span style={{ fontSize: '11px', color: '#64748b', fontWeight: 'normal' }}>(Optional)</span>
            </label>
            <input 
              type="tel" 
              placeholder="10-digit mobile number" 
              value={mobile}
              onChange={e => setMobile(e.target.value)}
              style={{ 
                width: '100%', 
                padding: '14px 16px', 
                borderRadius: '14px', 
                border: '1px solid var(--color-border)', 
                backgroundColor: '#ffffff',
                fontSize: '15px' 
              }}
            />
          </div>

          <button 
            type="submit" 
            disabled={loading}
            style={{ 
              marginTop: '10px',
              background: '#F8CB46', 
              color: '#000000', 
              padding: '16px', 
              borderRadius: '14px', 
              border: 'none', 
              fontWeight: '800', 
              fontSize: '16px',
              cursor: loading ? 'not-allowed' : 'pointer',
              boxShadow: '0 4px 16px rgba(248, 203, 70, 0.4)',
              transition: 'transform 0.15s ease'
            }}
          >
            {loading ? 'Verifying Code...' : 'Access Delivery Dashboard'}
          </button>
        </form>
      </div>
    </div>
  );
}
